# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\"\x16\n\x06\x43lient\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"C\n\x0b\x43hatMessage\x12\x13\n\x0bsender_name\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x05\x32\x7f\n\x0b\x43hatService\x12#\n\x0bSendMessage\x12\x0c.ChatMessage\x1a\x06.Empty\x12(\n\x0eReceiveMessage\x12\x06.Empty\x1a\x0c.ChatMessage0\x01\x12!\n\x0eRegisterClient\x12\x07.Client\x1a\x06.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENT._serialized_start=14
  _CLIENT._serialized_end=36
  _EMPTY._serialized_start=38
  _EMPTY._serialized_end=45
  _CHATMESSAGE._serialized_start=47
  _CHATMESSAGE._serialized_end=114
  _CHATSERVICE._serialized_start=116
  _CHATSERVICE._serialized_end=243
# @@protoc_insertion_point(module_scope)
